[workspace]
members = [
    "psyche",
    "psyched",
    "whisperd",
    "rememberd",
    "daemon-common",
    "stream_prefix",
    "distilld",
    "spoken",
    "seen",
    "would",
    "faced",
]
resolver = "2"
