use crate::{Impression, Intention};

/// Event emitted from [`Wit`] or [`Will`].
#[derive(Debug)]
pub enum PsycheEvent<T = serde_json::Value> {
    /// Batch of impressions generated by a [`Wit`].
    Impressions(Vec<Impression<T>>),
    /// Intentions produced by a [`Will`].
    Intentions(Vec<Intention>),
}
