[package]
name = "daringsby"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
psyche-rs = { path = "../psyche-rs" }
tokio = { version = "1", features = ["macros", "rt"] }
clap = { version = "4", features = ["derive"] }
rand = "0.8"
tracing = "0.1"
tracing-subscriber = "0.3"
chrono = "0.4"
futures = "0.3"
async-stream = "0.3"
async-trait = "0.1"
ollama-rs = { version = "0.3.2", features = ["stream"] }
once_cell = "1"
serde_json = "1"
include_dir = "0.7"
reqwest = { version = "0.12", features = ["stream"] }
segtok = "0.1.5"
urlencoding = "2"
bytes = "1"

[dev-dependencies]
httpmock = "0.7"
tokio = { version = "1", features = ["macros", "rt"] }
futures = "0.3"

[features]
moment-feedback = []
