[package]
name = "daringsby"
version = "0.1.0"
edition = "2024"

[dependencies]
psyche-rs = { path = "../psyche-rs" }
tokio = { version = "1", features = ["macros", "rt"] }
clap = { version = "4", features = ["derive"] }
rand = "0.8"
tracing = "0.1"
tracing-subscriber = "0.3"
chrono = "0.4"
futures = "0.3"
async-stream = "0.3"
async-trait = "0.1"
llm = "1.3.1"
