[package]
name = "daringsby"
version = "0.1.0"
edition = "2024"

[dependencies]
psyche-rs = { path = "../psyche-rs" }
anyhow = "1.0"
llm = "1.3"
neo4rs = "0.5"
tokio = { version = "1", features = ["rt", "macros"] }
tracing-subscriber = "0.3"
