[package]
name = "daringsby"
version = "0.1.0"
edition = "2024"

[dependencies]
psyche-rs = { path = "../psyche-rs" }
anyhow = "1.0"
llm = "1.3"
neo4rs = "0.5"
tokio = { version = "1", features = ["full"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
axum = { version = "0.7", features = ["ws"] }
tokio-util = "0.7"
tower = "0.4"
bytes = "1"
futures-util = "0.3"
tracing = "0.1"
