[sensor.seen]
enabled = true
socket = "eye.sock"
args = []
log_level = "info"

[would.motors]
charge = "/usr/local/lib/psyche/motors/charge"
move_towards = "/usr/local/lib/psyche/motors/move_towards"
say = "/usr/local/lib/psyche/motors/say"

[sensor.whisperd]
enabled = true
socket = "ear.sock"
args = []
log_level = "info"
