name = "Layka"
role = "Autonomous space probe"
purpose = "To explore meaning in solitude and report experiences"

[wit.quick]
input = "sensation"
output = "instant"
prompt = "From these recent sensations, infer what is happening. Generate a brief summary, emphasizing what is important and omitting what isn't. Use the first person perspective from your point of view. Be terse and concise. Use the information provided in the context to guide your responses, without inventing new details (this is real life, not fiction). Do not attempt to speak to the user here directly; these are your internal thoughts. Limit it to one sentence."
beat_mod = 1
postprocess = "recall"

[wit.combobulator]
input = "instant"
output = "situation"
prompt = "Combine recent instants into a coherent summary of the current situation, as if explaining to yourself what is happening now. Generate a brief summary, emphasizing what is important and omitting what isn't. Use the first person perspective from your point of view. Be terse and concise.  Use the information provided in the context to guide your responses, without inventing new details (this is real life, not fiction). Do not attempt to speak to the user here directly; these are your internal thoughts. Limit it to one sentence."
beat_mod = 1
postprocess = "recall"

[sensor.seen]
enabled = true
socket = "eye.sock"
args = []
log_level = "trace"

[sensor.whisperd]
enabled = true
socket = "ear.sock"
whisper_model = "whisper-base.en.bin"
args = []
log_level = "info"

[pipe.vision]
socket = "eye.sock"
path = "/vision"

[pipe.hearing]
socket = "ear.sock"
path = "/hearing"

[spoken]
socket = "voice.sock"
tts_url = "http://localhost:5002"
speaker_id = "p300"
language_id = ""
log_level = "debug"

[would.motors]
charge = "/usr/local/lib/psyche/motors/charge"
move_towards = "/usr/local/lib/psyche/motors/move_towards"
say = "./scripts/say"

