#!/bin/sh

if [ -z "$1" ]; then
    set -- "layka"
fi

# Start spoken alongside psyched
./scripts/spoken &
SPOKEN_PID=$!

# Run the psyche daemon in development mode
cargo run -p psyched -- --soul all_souls/$1 --socket ./quick.sock --log-level debug

kill $SPOKEN_PID
