#!/bin/sh

if [ -z "$1" ]; then
    set -- "layka"
fi

# Run the psyche daemon in development mode
cargo run -p psyched -- --soul all_souls/$1 --socket ./quick.sock --log-level trace --qdrant-url http://localhost:6333 --neo4j-url http://localhost:7474 --neo4j-user neo4j --neo4j-pass password
