[[llm]]
provider = "ollama"
base_url = "http://10.0.0.180:11434"
models = ["gemma3:27b", "gemma3n", "phi4"]

[[llm]]
provider = "ollama"
base_url = "http://192.168.1.123:11434"
models = ["gemma3:27b", "gemma3n", "phi4"]
