[[llm]]
provider = "ollama"
base_url = "http://localhost:11434"
models = ["gemma3:27b", "gemma3n", "phi4"]

[[llm]]
provider = "ollama"
base_url = "http://localhost:11434"
models = ["gemma3:27b", "gemma3n", "phi4"]
